<div class="footer">
    <div class="regular-padding k2d-thin">
        <a href="./pages/sign_up.php">Join Us</a> |
        <a href="./pages/sign_in.php">Login</a> |
        <a href="./pages/contact.php">Contact</a> |

        <a href="./pages/terms_of_service.php">Terms of Service</a> |
        <a href="./pages/privacy_policy.php">Privacy Policy</a>

    </div>
    <div class="regular-padding k2d-thin""><span>&copy; <?php echo date('Y'); ?> Ross Clayton Cramer</span>
    </div>
    <div class=" regular-padding">
        <script type='text/javascript' src='https://storage.ko-fi.com/cdn/widget/Widget_2.js'></script>
        <script
            type='text/javascript'>kofiwidget2.init('Support Me on Ko-fi', '#696969', 'Z8Z8U8DOT'); kofiwidget2.draw();</script>
    </div>
</div>