<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title><?php echo $page_title ?></title>
  <link rel="icon" href="/favicon.png" />
  <!-- <link
    href="https://fonts.googleapis.com/css2?family=Julius+Sans+One&family=K2D:ital,wght@0,100;0,200;0,300;0,400;0,500&display=swap"
    rel="stylesheet" /> -->
  <link rel="stylesheet" href="<?php echo $stylesheet ?>" />
  <link rel="stylesheet" href="<?php echo $lightTheme ?>" />
</head>

<body>
