<div class="regular-padding narrow">
    <div class="indent-wide">
        <h3>Select a Feature:</h3>
        <p>Use the dropdown menu to find a feature located in Big Sur, including California State Parks, Los Padres National Forest Monterey District, the Ventana Wilderness, and other noteworthy locations.</p>
    </div>

    <div class="indent-wide">
        <h3>View the Trail Map:</h3>
        <p>Open the trail map to quickly locate a position and explore the surrounding area.</p>
    </div>
    <div class="indent-wide">
        <h3>Share and Read the Latest Trail Conditions:</h3>
        <p>Submit a trail report to help others access and enjoy the Underused Sur. Many of these locations are lost, and many more are facing an immediate risk of being lost due to lack of use, absence of oversight, the changing climate, and political opposition to their existence.</p>
    </div>
</div>
