<div class="regular-padding narrow">
    <div class="indent-wide">
        <h3>Find Your Trail:</h3>
        <p>Use the dropdown menu to find a feature in Big Sur, including California State Parks, Los Padres National Forest, Monterey District, the Ventana Wilderness, and other noteworthy locations.</p>
    </div>

    <div class="indent-wide">
        <h3>Explore the Topographic Trail Map:</h3>
        <p>Open the trail map to quickly locate trails and explore the surrounding area.</p>
    </div>
    <div class="indent-wide">
        <h3>Discover Hidden Gems:</h3>
        <p>Share your trail experiences and help others discover underutilized, off-the-beaten-path locations in Big Sur. Many of these special places are at risk due to lack of use, neglect, climate change, and opposition to their preservation.</p>
    </div>
</div>
