<div class="regular-padding">

    <div class="regular-padding narrow">
        <div class="p1"></div>


        <div class="indent-wide margin-tall border-box-round regular-padding">

            <h3>Find Your Place</h3>

            <p>Use the dropdown menu to find a feature in Big Sur, including California State Parks, Los Padres National Forest Monterey District, the Ventana Wilderness, and other noteworthy locations.</p>
        </div>


        <div class="p2"></div>

        <div class="indent-wide margin-tall border-box-round regular-padding">
            <h3>Explore the Trail Map</h3>
            <p>Use the trail map to quickly locate trails and explore the surrounding area.</p>
        </div>


        <div class="p3"></div>

        <div class="indent-wide margin-tall border-box-round regular-padding">
            <h3>Discover Hidden Gems</h3>
            <p>Share your trail experiences and help others discover underutilized, off-the-beaten-path locations in Big Sur. Many of these special places are at risk due to lack of use, neglect, extreme weather, and opposition to their preservation.</p>
        </div>
    </div>
    <!-- <hr> -->
    <p><span class="em">Read the latest trail conditions from our community</span></p>
</div>