<h1>Privacy Policy</h1>
<h2>Welcome to bigsurtrailreport.net!</h2>
<p>
    We are committed to protecting your privacy. This Privacy Policy explains what information we collect, how we use
    it,
    and your rights concerning your data.</p>

<h3>1. Information We Collect</h3>
<p>
    We do not collect any personal information from users who simply browse our website. We may collect some
    non-personally
    identifiable information, such as:</p>
<p>
    <span class="em">Browsing data:</span> This may include information about your browser type, operating system, the
    pages you visit on our
    website, and the time of your visit. This data is collected anonymously and used in aggregate to analyze website
    usage
    and improve the user experience.
</p>

<h3>2. How We Use Your Information</h3>
<p>
    Any non-personally identifiable information we collect is used for the following purposes:
</p>
<ul>
    <li>
        <p>To understand how users interact with our website.</p>
    </li>
    <li>
        <p>To improve the functionality and content of the website.</p>
    </li>
    <li>
        <p>To generate anonymized reports on website traffic.</p>
    </li>
</ul>

<h3>3. We Do Not Sell or Share Your Data</h3>
<p>
    We do not sell or share your personal information with any third parties.


<h3>4. Your Rights</h3>
<p>
    As you do not provide any personal information, there is no specific data to delete or access. However, you can
    always
    choose to:</p>
<ul>
    <li>
        <p>Stop using our website.</p>
    </li>
</ul>
<h3>5. Children's Privacy</h3>
<p>
    Our website is not directed towards children under 13. We do not knowingly collect personal information from
    children
    under 13.</p>

<h3>6. Changes to this Privacy Policy</h3>
<p>
    We may update this Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy
    Policy
    on our website.</p>

<h3>7. Contact Us</h3>
<p>
    If you have any questions about this Privacy Policy, please <a href="./contact.php">contact</a> us.</p>