<div>
    <h1>Support Us</h1>
    <h2>Ways to Give</h2>
    <div class="section">
        <a href="https://www.instagram.com/bigsurrecreationcrew/" />
        <h3>Big Sur Recreation Crew</h3></a>
        <a href="https://www.instagram.com/bigsurrecreationcrew/" />
        <img src="../assets/images/rec-crew.png" /></a>
    </div>
    <div>
        <p><span class="em">The Big Sur Rec Crew</span> is a fantastic grassroots organization dedicated to maintaining
            the trails and promoting
            responsible outdoor recreation in Big Sur. They're a crew of passionate volunteers who rely on community
            support to keep doing their amazing work.</p>

        <h4>Here are a few ways you can contribute:</h4>
        <ul>
            <li>
                <p><span class="em"> Donate:</span> Every dollar helps! Financial contributions allow the Rec Crew to
                    purchase essential tools,
                    supplies, and fuel for their trail work.</p>
            </li>
            <li>
                <p><span class="em"> Donate in Kind:</span> Do you have gently used tools, outdoor clothing, or camping
                    equipment lying around?
                    The
                    Rec
                    Crew can put them to good use!</p>
            </li>
            <li>
                <p><span class="em"> Fuel the Crew:</span> Donating food and drinks helps keep the volunteers energized
                    during long days on
                    the
                    trails.</p>
            </li>
        </ul>



        <h4>Want to get even more involved?</h4>
        <p>Head over to the Big Sur Rec Crew's Instagram page <a
                href="https://www.instagram.com/bigsurrecreationcrew/">Big Sur Rec Crew</a> and send them a direct
            message! They're
            always happy to chat with potential volunteers and find ways for
            everyone to contribute their skills and passions to this amazing cause. Together, we can ensure Big Sur's
            trails remain beautiful and welcoming for generations to come!</p>
    </div>

    <hr>

    <h3>Keep the Trails Updated: Support Our Website!</h3>
    <p>
        This website is a valuable resource for anyone planning a trip to Big Sur's beautiful backcountry. We strive to
        provide up-to-date trail reports, local knowledge, and helpful tools to make your outdoor adventure safe and
        enjoyable.</p>
    <div class="profile">
        <img src="../assets/images/profile.png" alt="" Ross Clayton Cramer" />
    </div>

    <script type='text/javascript' src='https://storage.ko-fi.com/cdn/widget/Widget_2.js'></script>
    <script
        type='text/javascript'>kofiwidget2.init('Support Me on Ko-fi', '#57a773', 'Z8Z8U8DOT'); kofiwidget2.draw();</script>
    <h4>Community Funded for the Community:</h4>
    <p>
        Maintaining and updating this website takes time and resources.<span class="em"> We are proud to say that
            this website is
            entirely
            community-funded through your generous support.</span> Your contributions allow us to keep the information
        fresh, the
        maps
        accurate, and the site accessible to everyone. By supporting us, you're directly contributing to the value of
        this
        project for the entire Big Sur community.

        Every contribution, big or small, makes a difference. Please consider donating to help us continue providing
        this
        valuable resource.</p>

</div>