<div class="tos">
    <h1>Terms of Service<h1>
            <h2>Welcome to bigsurtrailreports.net!</h2>

            <p>
                These Terms of Service govern your access to and use of the website operated by bigsurtrailreports.net.
                These
                Terms apply to all visitors, users, and others who access or use the Service (as defined below).
            </p>
            <p>
                Please read these Terms carefully before accessing or using our Service.
            </p>
            <p>
                By accessing or using the Service, you agree to be bound by these Terms. If you disagree with any part
                of
                the
                Terms, then you may not access or use the Service.</p>

            <h3>1. Definitions</h3>
            <p>
                Service means the bigsurtrailreports.net website, its content, features, and functionalities, offered by
                bigsurtrailreports.net.</p>
            <p>
                Content means all text, data, graphics, images, video, audio, or other materials displayed or available
                on
                the
                Service.</p>
            <p>
                User means the individual accessing or using the Service, or on whose behalf the Service is being
                accessed
                or
                used.</p>
            <h3>2. Use of the Service</h3>
            <p>
                You agree to use the Service only for lawful purposes and in accordance with these Terms.</p>

            <h4> You agree not to use the Service:</h4>
            <p>
                In a way that violates any applicable law or regulation.</p>
            <p>
                For the purpose of exploiting, harming, or attempting to exploit or harm minors in any way.
                To transmit, or procure the transmission of, any material that is harassing, offensive, defamatory,
                infringing,
                obscene, or otherwise objectionable.</p>
            <p>
                To interfere with or disrupt the Service or servers or networks connected to the Service.
                To impersonate any person or entity, or to falsely state or otherwise misrepresent your affiliation with
                a
                person or entity.</p>
            <p>
                To gain unauthorized access to the Service, the computer systems of others, or other restricted systems.
                To attempt to disable or circumvent any security measures of the Service.</p>
            <h3>3. User Content</h3>

            <p>
                The Service may allow you to post, submit, store, or transmit content. You retain all ownership rights
                to
                your
                User Content. By posting User Content, you grant us a non-exclusive, royalty-free, worldwide license to
                use,
                modify, publish, or translate your User Content for the sole purpose of providing and improving the
                Service.
            </p>
            <h3>
                4. Disclaimers</h3>
            <p>
                The Content on the Service is provided for informational purposes only.</p>
            <p>
                We do not guarantee the accuracy, completeness, or timeliness of the Content.
                You rely on the Content at your own risk.
                The Service is provided "as is" and "as available" without any warranties of any kind, express or
                implied.
            </p>
            <p>
                We disclaim all warranties, express or implied, including but not limited to, implied warranties of
                merchantability, fitness for a particular purpose, non-infringement, and security.
            </p>
            <p>
                We do not warrant that the Service will be uninterrupted, secure, or error-free.
                We do not warrant that the results that may be obtained from the use of the Service will be accurate or
                reliable.</p>
            <h3> 5. Limitation of Liability</h3>
            <p>
                To the extent permitted by law, we shall not be liable for any direct, indirect, incidental,
                consequential,
                or
                special damages arising out of or in any way connected with your use of the Service or the Content.
            </p>
            <p>
                This includes, without limitation, damages for loss of profits, loss of data, or business interruption.
            </p>
            <h3>
                6. Intellectual Property</h3>
            <p>
                The Service and its original content (excluding User Content) are owned by us or our licensors and are
                protected
                by international copyright and other intellectual property laws.</p>
            <p>
                You may not modify, publish, distribute, transmit, reverse engineer, create derivative works of, or
                exploit
                in
                any way the Service or its content without our prior written consent.</p>

            <h3>7. Termination</h3>
            <p>
                We may terminate or suspend your access to the Service immediately, without prior notice or liability,
                for
                any
                reason whatsoever, including without limitation if you breach these Terms.
            </p>
            <p>
                Upon termination, your right to use the Service will immediately cease.
            </p>
            <h3> 8. Governing Law</h3>
            <p>
                These Terms shall be governed and construed in accordance with the laws of California without regard to
                its
                conflict of law provisions.</p>
            <h3>
                9. Entire Agreement</h3>
            <p>
                These Terms constitute the entire agreement between you and us regarding our Service and supersede all
                prior
                and
                contemporaneous communications and proposals, whether oral or written.
            </p>
            <h3>
                10. Changes to the Terms</h3>
            <p>
                We reserve the right to update or change these Terms at any time. We will notify you of any changes by
                posting
                the new Terms on the Service. You are advised to review these Terms periodically for any changes.
                Your continued use of the Service after the posting of any revised Terms signifies your acceptance of
                the
                new
                Terms.</p>

            <h3>11. Contact Us</h3>
            <p>
                If you have any questions about these Terms, please <a href="./contact.php">contact</a> us.</p>
</div>